# Generated by Django 3.2.4 on 2021-06-05 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='arc_img', verbose_name='arc_image')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='chapter_title')),
                ('chapter', models.TextField(verbose_name='chapter')),
                ('image', models.ImageField(upload_to='chapter_img', verbose_name='chapter_image')),
                ('number', models.IntegerField()),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.arc', verbose_name='arc')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
