# Generated by Django 3.2.4 on 2021-06-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210605_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
