# Generated by Django 3.2.4 on 2021-06-08 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_chapter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='name',
            field=models.CharField(max_length=30, verbose_name='arc_name'),
        ),
        migrations.AlterField(
            model_name='arc',
            name='number',
            field=models.IntegerField(verbose_name='arc_number'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(verbose_name='chapter_number'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published_at'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
    ]
