# Generated by Django 3.2.4 on 2021-06-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_chapter_arc'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
