# Generated by Django 3.2.4 on 2021-06-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_chapter_en_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_slug',
            new_name='slug',
        ),
    ]
