# Generated by Django 3.2.4 on 2021-06-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.chapter'),
        ),
    ]
