# Generated by Django 3.2.4 on 2021-06-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comment_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replaying_to',
        ),
    ]
