# Generated by Django 3.2.4 on 2021-06-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_replaying_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replaying_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
